[project]
name = "vienna-transport"
version = "0.1.0"
description = "MCP server for Vienna public transportation data using Wiener Linien API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
