[project]
name = "stockholm-transport"
version = "0.1.0"
description = "MCP server for Stockholm public transportation data using Trafiklab Realtime API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
