apiVersion: v1
kind: Service
metadata:
  name: mcp-stockholm-transport
  labels:
    {{- include "mcp-stockholm-transport.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-stockholm-transport.selectorLabels" . | nindent 4 }}